---
- hosts: webservers 
  become: True
  tasks:
    - name: Copy petclinic.jar from the Jenkins build server to Web server
      copy:
        src: target
        dest: /home/ubuntu/
        force: yes