---
- hosts: webservers 
  become: True
  tasks:
    - name: Copy petclinic.jar from the Jenkins build server to Web server
      copy:
        src: target
        dest: /home/ubuntu/
        force: yes
    
    - name: Execute petclinic and display welcome screen
      shell: |
        sudo kill $(sudo lsof -t -i:8080)
        java -jar target/*.jar